/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        ink: "#161B26",
        "ink-muted": "#5C6578",
        "ink-faint": "#8B93A7",
        paper: "#F4F5F7",
        "paper-raised": "#FFFFFF",
        rule: "#E2E5EB",
        "rule-strong": "#C5CAD6",
        stamp: "#B91C2C",
        "stamp-soft": "#F8E8EA",
        caution: "#9A6B12",
        "caution-soft": "#F5EEDF",
        quiet: "#3D526B",
        "quiet-soft": "#E8EEF5",
        ok: "#1F6B4A",
        "ok-soft": "#E4F0EA",

        // Compatibility aliases → semantic tokens
        primary: "#161B26",
        "on-primary": "#FFFFFF",
        "primary-container": "#2A3344",
        "on-primary-container": "#A8B0C2",
        "primary-fixed": "#E8EEF5",
        "primary-fixed-dim": "#D5DEEA",
        "on-primary-fixed": "#161B26",
        "on-primary-fixed-variant": "#3D526B",
        secondary: "#3D526B",
        "on-secondary": "#FFFFFF",
        "secondary-fixed": "#E8EEF5",
        "secondary-fixed-dim": "#D5DEEA",
        "on-secondary-fixed": "#161B26",
        "on-secondary-fixed-variant": "#3D526B",
        "secondary-container": "#E8EEF5",
        "on-secondary-container": "#161B26",
        background: "#F4F5F7",
        "on-background": "#161B26",
        surface: "#F4F5F7",
        "surface-bright": "#FFFFFF",
        "surface-dim": "#E8EAEE",
        "surface-container": "#EEF0F3",
        "surface-container-low": "#F4F5F7",
        "surface-container-high": "#E8EAEE",
        "surface-container-highest": "#DEE1E7",
        "surface-container-lowest": "#FFFFFF",
        "surface-variant": "#E8EAEE",
        "surface-tint": "#3D526B",
        "on-surface": "#161B26",
        "on-surface-variant": "#5C6578",
        outline: "#C5CAD6",
        "outline-variant": "#E2E5EB",
        "border-subtle": "#E2E5EB",
        "legal-text": "#2A3140",
        "critical-red": "#B91C2C",
        "warning-gold": "#9A6B12",
        "success-green": "#1F6B4A",
        error: "#B91C2C",
        "error-container": "#F8E8EA",
        "on-error": "#FFFFFF",
        "on-error-container": "#7F121F",
        tertiary: "#9A6B12",
        "on-tertiary": "#FFFFFF",
        "tertiary-fixed": "#F5EEDF",
        "tertiary-fixed-dim": "#E8D9B8",
        "on-tertiary-fixed": "#3D2A08",
        "on-tertiary-fixed-variant": "#6B4A10",
        "tertiary-container": "#3D2A08",
        "on-tertiary-container": "#E8D9B8",
        "inverse-surface": "#161B26",
        "inverse-on-surface": "#F4F5F7",
        "inverse-primary": "#D5DEEA",
      },
      borderRadius: {
        DEFAULT: "8px",
        sm: "6px",
        md: "8px",
        lg: "12px",
        xl: "16px",
        full: "9999px",
      },
      spacing: {
        gutter: "12px",
        unit: "4px",
        "section-gap": "24px",
        "card-padding": "16px",
        "container-padding": "20px",
        content: "1120px",
      },
      maxWidth: {
        content: "1120px",
      },
      fontFamily: {
        sans: ['"Be Vietnam Pro"', "system-ui", "sans-serif"],
        display: ['"Be Vietnam Pro"', "system-ui", "sans-serif"],
        "label-bold": ['"Be Vietnam Pro"', "sans-serif"],
        "mono-legal": ['"Be Vietnam Pro"', "sans-serif"],
        "headline-md": ['"Be Vietnam Pro"', "sans-serif"],
        "label-sm": ['"Be Vietnam Pro"', "sans-serif"],
        "body-lg": ['"Be Vietnam Pro"', "sans-serif"],
        "headline-sm": ['"Be Vietnam Pro"', "sans-serif"],
        "body-md": ['"Be Vietnam Pro"', "sans-serif"],
        "display-lg": ['"Be Vietnam Pro"', "sans-serif"],
      },
      fontSize: {
        // Refined, compact SaaS scale (mobile-first; bump slightly at md via components)
        "label-bold": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "mono-legal": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-md": ["15px", { lineHeight: "22px", fontWeight: "500", letterSpacing: "-0.01em" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "500", letterSpacing: "0.03em" }],
        "body-lg": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-sm": ["13px", { lineHeight: "18px", fontWeight: "500", letterSpacing: "-0.01em" }],
        "body-md": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg": ["18px", { lineHeight: "24px", letterSpacing: "-0.02em", fontWeight: "500" }],
        // Utility aliases
        page: ["1.125rem", { lineHeight: "1.35", letterSpacing: "-0.02em", fontWeight: "500" }],
        section: ["0.9375rem", { lineHeight: "1.4", letterSpacing: "-0.01em", fontWeight: "500" }],
        ui: ["0.8125rem", { lineHeight: "1.45", fontWeight: "400" }],
        meta: ["0.6875rem", { lineHeight: "1.35", fontWeight: "500", letterSpacing: "0.02em" }],
      },
      screens: {
        xs: "400px",
      },
      boxShadow: {
        sm: "0 1px 2px rgba(22, 27, 38, 0.04)",
        card: "0 1px 3px rgba(22, 27, 38, 0.06), 0 1px 2px rgba(22, 27, 38, 0.04)",
        lift: "0 8px 24px -12px rgba(22, 27, 38, 0.16)",
        dossier: "0 1px 3px rgba(22, 27, 38, 0.06)",
      },
      keyframes: {
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(6px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "dossier-in": {
          "0%": { opacity: "0", transform: "translateY(6px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "fade-in": "fade-in 280ms cubic-bezier(0.22, 1, 0.36, 1) both",
        "dossier-in": "fade-in 280ms cubic-bezier(0.22, 1, 0.36, 1) both",
      },
    },
  },
  plugins: [],
};
