from typing import Any, Protocol
from uuid import UUID

from app.domain.entities.contract import Contract, ContractChunk
from app.domain.entities.legal import (
    LegalChunk,
    LegalChunkRelation,
    LegalDocRelation,
    LegalDocument,
)
from app.domain.entities.user import User


class UserRepository(Protocol):
    def create(self, email: str, password_hash: str) -> User: ...
    def get_by_email(self, email: str) -> User | None: ...
    def get_by_id(self, user_id: UUID) -> User | None: ...


class ContractRepository(Protocol):
    def upsert(self, contract: Contract) -> None: ...
    def get(self, contract_id: str) -> Contract | None: ...
    def get_owned(self, contract_id: str, user_id: UUID) -> Contract | None: ...
    def list_by_user(self, user_id: UUID) -> list[Contract]: ...
    def save_analysis(self, contract_id: str, analysis: dict[str, Any], risks: list[Any]) -> None: ...


class ContractChunkRepository(Protocol):
    def replace_for_contract(self, contract_id: str, chunks: list[ContractChunk]) -> None: ...
    def list_contents(self, contract_id: str) -> list[str]: ...
    def get_text_by_clause(self, contract_id: str, clause_number: str) -> str | None: ...


class LegalDocumentRepository(Protocol):
    def upsert(self, doc: LegalDocument) -> None: ...
    def get(self, doc_id: str) -> LegalDocument | None: ...
    def upsert_relations(self, relations: list[LegalDocRelation]) -> None: ...


class LegalChunkRepository(Protocol):
    def upsert_many(self, chunks: list[LegalChunk]) -> None: ...
    def upsert_relations(self, relations: list[LegalChunkRelation]) -> None: ...
    def get_texts_by_refs(self, chunk_refs: list[str]) -> dict[str, str]: ...
    def get_meta_by_refs(self, chunk_refs: list[str]) -> dict[str, dict[str, Any]]: ...
    def count_for_doc(self, doc_id: str) -> int: ...
